### ISSUE TITLE
Residual "wind" tech call

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#156]
**Bug Description**
The offshore module fails from a call using the technology flag "wind" while expecting "windpower" [here](https://github.com/NREL/reV/blob/master/reV/offshore/offshore.py#L828).

**Full Traceback**
(/home/twillia2/.conda-envs/weto) [twillia2@ed5 stdout]$ cat outputs_offshore_99_3020800.e
Traceback (most recent call last):
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/site-packages/NREL_reV-0.3.0-py3.7.egg/reV/offshore/cli_offshore.py", line 250, in <module>
    main(obj={})
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/site-packages/NREL_reV-0.3.0-py3.7.egg/reV/offshore/cli_offshore.py", line 146, in main
    raise e
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/site-packages/NREL_reV-0.3.0-py3.7.egg/reV/offshore/cli_offshore.py", line 142, in main
    fpath_out=fpath_out)
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/site-packages/NREL_reV-0.3.0-py3.7.egg/reV/offshore/offshore.py", line 829, in run
    sites_per_worker=100)
  File "/home/twillia2/.conda-envs/rev/lib/python3.7/site-packages/NREL_reV-0.3.0-py3.7.egg/reV/generation/generation.py", line 860, in get_pc
    .format(tech, list(Gen.OPTIONS.keys())))
KeyError: 'Did not recognize gen tech "wind". Gen options are: [\'pv\', \'csp\', \'solarwaterheat\', \'troughphysicalheat\', \'lineardirectsteam\', \'windpower\']'

**System (please complete the following information):**
 - Eagle

**Additional context**

**Comment by MRossol** [comment]
@WilliamsTravis I just pushed a bug fix to master and updated the module on Eagle, can you try again?

**Comment by WilliamsTravis** [comment]
Okay, great thanks.
