### ISSUE TITLE
Collect CLI Option Error

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#174]
**Bug Description**

Collect module fails with the error:

Usage: cli_collect.py [OPTIONS] COMMAND [ARGS]...
Try 'cli_collect.py --help' for help.

Error: no such option: -f

However, running the same configuration with reV 0.3.1 runs as expected.

**Full Traceback**
Traceback (most recent call last):
  File "/shared-projects/rev/modulefiles/conda_env/bin/reV", line 11, in <module>
    load_entry_point('NREL-reV', 'console_scripts', 'reV')()
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/lustre/eaglefs/shared-projects/rev/modulefiles/gitrepos/reV/reV/cli.py", line 100, in pipeline
    cancel=cancel, monitor=monitor, verbose=verbose)
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/lustre/eaglefs/shared-projects/rev/modulefiles/gitrepos/reV/reV/pipeline/cli_pipeline.py", line 43, in from_config
    Pipeline.run(config_file, monitor=monitor, verbose=verbose)
  File "/lustre/eaglefs/shared-projects/rev/modulefiles/gitrepos/reV/reV/pipeline/pipeline.py", line 499, in run
    pipe._main()
  File "/lustre/eaglefs/shared-projects/rev/modulefiles/gitrepos/reV/reV/pipeline/pipeline.py", line 109, in _main
    .format(i, module, f_config))
reV.utilities.exceptions.ExecutionError: reV pipeline failed at step 1 "collect" /lustre/eaglefs/shared-projects/rev/projects/iraq/rev/solar/generation/config_collect.json

**Expected behavior**
reV-collect merges all generation output chunks into a single file for each year and stores the chunk files separately. 

**System (please complete the following information):**
 - OS: Linux
 - Compute hardware: Eagle
 - Version: 0.4.2

**Comment by MRossol** [comment]
@WilliamsTravis this should be fixed, updating modules now

**Comment by grantbuster** [comment]
@MRossol and @WilliamsTravis  can we close this?

**Comment by WilliamsTravis** [comment]
Hey, the last test I ran this morning got a similar (but different) error:

(/home/twillia2/.conda-envs/rev) [twillia2@ed1 stdout]$ cat collect_generation_gen_2016_3387395.e
Usage: cli_collect.py direct [OPTIONS] COMMAND [ARGS]...
Try 'cli_collect.py direct --help' for help.

Error: Missing command.

**Comment by WilliamsTravis** [comment]
Let me try one more time in case it was me. I got stuck in the queue this morning.

**Comment by MRossol** [comment]
@WilliamsTravis give me a sec to integrate a commit. I think I missed a format variable

**Comment by grantbuster** [comment]
@MRossol, I think this should have two commands right? direct and then collect?

https://github.com/NREL/reV/blob/bdf164e8e42994732978d4eaf8b3f441add782f0/reV/handlers/cli_collect.py#L257

should be: 

'python -m reV.handlers.cli_collect {arg_main} direct collect'

**Comment by MRossol** [comment]
good catch @grantbuster, added collect

**Comment by WilliamsTravis** [comment]
Try again?

**Comment by MRossol** [comment]
@WilliamsTravis Yes, module env is updated

**Comment by WilliamsTravis** [comment]
Okay, it works. Thanks!
