### ISSUE TITLE
Windpower looks for non existing test data

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#188]
**Bug Description**
For conda installations, the windpower SAM module is looking for non-existing test data in the site packages folder before running. Copying this data from the repo into the site-packages/tests folder fixes the problem, though it seems odd that it needs this.

**Full Traceback**
(/home/twillia2/.conda-envs/rr) [twillia2@el2 tests]$ cat /lustre/eaglefs/shared-projects/rev/projects/soco/rev/runs/reference/generation/120hh/20ps/logs/stdout/20ps_gen_2007_00_3906721.e
/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/reV/generation/generation.py:310: OutputWarning: User output request "mean_ws" not recognized. Will attempt to extract from PySAM.
  warn(msg, OutputWarning)
Traceback (most recent call last):
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/reV/generation/cli_gen.py", line 650, in <module>
    main(obj={})
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/reV/generation/cli_gen.py", line 336, in gen_local
    timeout=timeout)
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/reV/generation/generation.py", line 1450, in reV_run
    downscale=downscale)
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/reV/generation/generation.py", line 281, in __init__
    self._init_out_arrays()
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/reV/generation/generation.py", line 526, in _init_out_arrays
    self._out_chunk = (index_0, np.min((index_0 + self.site_limit,
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/reV/generation/generation.py", line 591, in site_limit
    self._site_limit = int(np.floor(avail_mem / self.site_mem))
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/reV/generation/generation.py", line 621, in site_mem
    shape = self._get_data_shape(request, n)
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/reV/generation/generation.py", line 412, in _get_data_shape
    self._sam_obj_default = init_obj.default
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/reV/SAM/generation.py", line 1084, in default
    self._default = DefaultWindPower.default()
  File "/home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/reV/SAM/defaults.py", line 85, in default
    obj.execute()
Exception: windpower execution error. exec fail(windpower): failed to read local weather file: /home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/tests/data/SAM/WY Southern-Flat Lands.csv could not open file for reading: /home/twillia2/.conda-envs/rr/lib/python3.7/site-packages/tests/data/SAM/WY Southern-Flat Lands.csv

**System (please complete the following information):**
 - OS: Linux
 - Compute hardware: Eagle
 - Version: 0.4.4

**Comment by MRossol** [comment]
@WilliamsTravis Good catch, moving the defaults into the SAM sub-package. Running tests and then will re-release.

**Comment by WilliamsTravis** [comment]
Cool, thanks.

**Comment by MRossol** [comment]
fixed
