### ISSUE TITLE
Maximum recursion depth error in multi-year QAQC

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#213]
**Bug Description**
When running QAQC after running generation and multi-year, QAQC completes most (or all?) of the checks, but fails with a maximum recursion depth exceeded error.

**Full Traceback**
```
INFO - 2020-09-25 09:34:29,505 [cli_qa_qc.py:371] : Running reV supply curve from config file: "/lustre/eaglefs/shared-projects/rev
/projects/heco/rev/gen_pv_tracking/config_qa-qc.json"
INFO - 2020-09-25 09:34:29,505 [cli_qa_qc.py:371] : Running reV supply curve from config file: "/lustre/eaglefs/shared-projects/rev
/projects/heco/rev/gen_pv_tracking/config_qa-qc.json"
INFO - 2020-09-25 09:34:29,506 [cli_qa_qc.py:372] : Target output directory: "/lustre/eaglefs/shared-projects/rev/projects/heco/rev
/gen_pv_tracking/"
INFO - 2020-09-25 09:34:29,506 [cli_qa_qc.py:372] : Target output directory: "/lustre/eaglefs/shared-projects/rev/projects/heco/rev
/gen_pv_tracking/"
INFO - 2020-09-25 09:34:29,506 [cli_qa_qc.py:373] : Target logging directory: "/lustre/eaglefs/shared-projects/rev/projects/heco/re
v/gen_pv_tracking/logs/"
INFO - 2020-09-25 09:34:29,506 [cli_qa_qc.py:373] : Target logging directory: "/lustre/eaglefs/shared-projects/rev/projects/heco/re
v/gen_pv_tracking/logs/"
INFO - 2020-09-25 09:34:29,508 [cli_qa_qc.py:639] : Running reV QA-QC on SLURM with node name "gen_pv_tracking_QA-QC"
INFO - 2020-09-25 09:34:29,508 [cli_qa_qc.py:639] : Running reV QA-QC on SLURM with node name "gen_pv_tracking_QA-QC"
INFO - 2020-09-25 09:34:30,109 [cli_qa_qc.py:663] : Kicked off reV QA-QC job "gen_pv_tracking_QA-QC" (SLURM jobid #4508014).
INFO - 2020-09-25 09:34:30,109 [cli_qa_qc.py:663] : Kicked off reV QA-QC job "gen_pv_tracking_QA-QC" (SLURM jobid #4508014).
INFO - 2020-09-25 09:34:41,296 [qa_qc.py:28] : QA/QC results to be saved to: /lustre/eaglefs/shared-projects/rev/projects/heco/rev/
gen_pv_tracking/QA_multi-year
INFO - 2020-09-25 09:34:41,298 [summary.py:31] : QAQC Summarize initializing on: /shared-projects/rev/projects/heco/rev/gen_pv_trac
king/gen_pv_tracking_multi-year.h5
ERROR - 2020-09-25 09:34:42,378 [qa_qc.py:135] : QAQC failed on file: gen_pv_tracking_multi-year.h5. Received exception:
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/ngrue/.conda-envs/revenv/lib/python3.7/site-packages/reV/qa_qc/qa_qc.py", line 132, in h5
    **kwargs)
  File "/home/ngrue/.conda-envs/revenv/lib/python3.7/site-packages/reV/qa_qc/qa_qc.py", line 87, in create_scatter_plots
    for file in os.listdir(self.out_dir):
  File "/home/ngrue/.conda-envs/revenv/lib/python3.7/site-packages/reV/qa_qc/qa_qc.py", line 43, in out_dir
    return self.out_dir
  File "/home/ngrue/.conda-envs/revenv/lib/python3.7/site-packages/reV/qa_qc/qa_qc.py", line 43, in out_dir
    return self.out_dir
  File "/home/ngrue/.conda-envs/revenv/lib/python3.7/site-packages/reV/qa_qc/qa_qc.py", line 43, in out_dir
    return self.out_dir
  [Previous line repeated 980 more times]
RecursionError: maximum recursion depth exceeded
```

**To Reproduce**
Steps to reproduce the problem behavior
Run pipeline at: `/shared-projects/rev/projects/heco/rev/gen_pv_tracking`

**Charge code**
WFED.11785.01.01.01

**Comment by grantbuster** [comment]
fixed in commit: https://github.com/NREL/reV/commit/bbd1aba5ccaae13ace933082f07997f5892c9b7e
PR: https://github.com/NREL/reV/pull/216
