### ISSUE TITLE
Aggregation Failing on National Runs

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#283]
**Bug Description**
The supply-curve-aggregation module is failing on national-scale runs with an out-of-memory error. This has been repeated with memory set to 90 & 179 GB, with versions 0.4.51 & 0.4.53, and has been replicated by @nickwg03. The last known working version is 0.4.49 (so it could have started with 0.4.50).

**Full Traceback**
Supply curve Aggregation failed. Received the following error:
A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/cli_sc_aggregation.py", line 355, in direct
    points_per_worker=points_per_worker)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/sc_aggregation.py", line 1547, in summary
    offshore_meta_cols=offshore_meta_cols)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/sc_aggregation.py", line 1388, in summarize
    points_per_worker=points_per_worker)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/sc_aggregation.py", line 1207, in run_parallel
    summary += future.result()
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Error running reV SC Aggregation CLI.
Traceback (most recent call last):
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/cli_sc_aggregation.py", line 540, in <module>
    main(obj={})
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/cli_sc_aggregation.py", line 360, in direct
    raise e
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/cli_sc_aggregation.py", line 355, in direct
    points_per_worker=points_per_worker)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/sc_aggregation.py", line 1547, in summary
    offshore_meta_cols=offshore_meta_cols)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/sc_aggregation.py", line 1388, in summarize
    points_per_worker=points_per_worker)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/sc_aggregation.py", line 1207, in run_parallel
    summary += future.result()
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/cli_sc_aggregation.py", line 540, in <module>
    main(obj={})
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/cli_sc_aggregation.py", line 360, in direct
    raise e
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/cli_sc_aggregation.py", line 355, in direct
    points_per_worker=points_per_worker)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/sc_aggregation.py", line 1547, in summary
    offshore_meta_cols=offshore_meta_cols)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/sc_aggregation.py", line 1388, in summarize
    points_per_worker=points_per_worker)
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/site-packages/reV/supply_curve/sc_aggregation.py", line 1207, in run_parallel
    summary += future.result()
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/shared-projects/rev/modulefiles/alternate_envs/revruns/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
slurmstepd: error: Detected 66 oom-kill event(s) in step 6222759.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Expected behavior**
The aggregation module aggregates and summarizes generation module outputs and creates a nice csv.

**System:**
 - OS: Linux
 - Compute hardware: Eagle
 - Version: 0.4.51 & 0.4.53

**Additional context**
This runs for about 40 minutes to an hour before it breaks. I ran it with debug and all of the log files are here: /shared-projects/rev/projects/awe/rev/aggregation/1_500kw_rigid_long_625m/logs

**Comment by MRossol** [comment]
@WilliamsTravis  and @nickwg03, I'm fairly certain this is due to changes made to EAGLE. Have you played with these options at all:
@click.option('--max_workers', '-mw', type=INT, default=None,
              show_default=True,
              help=("Number of cores to run summary on. None is all "
                    "available cpus"))
@click.option('--points_per_worker', '-ppw', type=INT, default=10,
              show_default=True,
              help="Number of sc_points to summarize on each worker")

**Comment by WilliamsTravis** [comment]
@MRossol, @nickwg03 Well, we've tried points_per_worker at 10, 100, & 200. I haven't tried adjusting the max workers option. I'll kick it off with half the workers and let you know what happens. 

However, this does work now with older reV versions (So Eagle changes included). Do you mean that recent changes in eagle might combine with recent changes in reV cause this?

**Comment by MRossol** [comment]
Whats "Old" because we haven't made any changes to sc_aggregation as of late, the only thing we changed was this:
https://github.com/NREL/reV/commit/c6f82ffff5cce0705d5d8e46effe371d334ddd5c#diff-bf3c0dcb47a46a6f4bbc0f86cff19d7ea29c6243c931ca20dc864bd1fc06f911

**Comment by WilliamsTravis** [comment]
Yesterday, I was successful with 0.4.10 (went way back to make sure because of a deadline, hadn't touched base with Nick yet). @nickwg03 last ran his successfully with 0.4.49 on March 10th.

**Comment by MRossol** [comment]
can you post the sc_agg configs (for 0.4.10, 0.4.49, and the one that failed)? The only thing that has changed since 0.4.49 is a refactor of TechMapping, but that's not getting run based on the logs...  Hence my confusion and suspicion that this is an EAGLE issue. I've been having tons of OOM errors on Eagle as of late...

**Comment by WilliamsTravis** [comment]
the one that worked for 0.4.10:

{
    "log_level": "DEBUG",
    "verbose": true,
    "directories": {
        "log_directories": "./logs",
        "output_directory": "./"
    },
    "cf_dset": "cf_mean-means",
    "excl_fpath": "/projects/rev/data/exclusions/Offshore_Exclusions.h5",
    "execution_control": {
        "allocation": "wetosa",
        "option": "eagle",
        "memory": 179,
        "walltime": 2.0,
	"max_workers": 10
    },
    "gen_fpath": "/shared-projects/rev/projects/awe/rev/generation/500kw/500kw_multi-year.h5",
    "res_class_dset": "ws_mean-means",
    "res_fpath": "/datasets/WIND/conus/v1.0.0/wtk_conus_{}.h5",
    "resolution": 128,
    "tm_dset": "techmap_wtk",
    "data_layers": {
        "lbnl_convex_hull_existing_farms_2018": {
            "dset": "lbnl_convex_hull_existing_farms_2018",
            "method": "sum"
        }
    },
    "excl_dict": {
        "nexrad_4km": {
            "exclude_values": [
                1
            ]
        },
        "albers": {
            "include_values": [
                1
            ]
        },
        "srr_lrr_9km": {
            "exclude_values": [
                1
            ]
        },
        "atlas_landform_elev_exclusion": {
            "exclude_values": [
                1
            ]
        },
        "all_land_25pct_slope_exclusion_srtm": {
            "exclude_values": [
                1
            ]
        },
        "open_access": {
            "exclude_values": [
                1
            ]
        },
        "airports_hsip_2015_10km_buffer": {
            "exclude_values": [
                1
            ]
        },
        "generic_setbacks_rails_625m": {
            "exclude_values": [
                1
            ]
        },
        "generic_setbacks_roads_625m": {
            "exclude_values": [
                1
            ]
        },
        "generic_setbacks_structures_625m": {
            "exclude_values": [
                1
            ]
        },
        "generic_setbacks_transmission_625m": {
            "exclude_values": [
                1
            ]
        }
    },
    "power_density": 0.636619772,
    "res_class_bins": null
}

**Comment by MRossol** [comment]
@WilliamsTravis, Can someone rerun the 0.4.49 config with the most recent version of reV or did you already try that?

**Comment by WilliamsTravis** [comment]
@MRossol Yeah, @nickwg03 did that just yesterday.

**Comment by MRossol** [comment]
Fixed in #267
