### ISSUE TITLE
Missing "kestrel" option in execution control

### ISSUE THREAD

**Issue by gabezuckerman** [NREL/reV#433]
**Bug Description**
Kestrel is missing from the list of execution control options. Discovered when running OSW LCP.

**Full Traceback**
```
Traceback (most recent call last):
  File "/kfs2/projects/rev/environments/gitrepos/reV/reV/config/base_analysis_config.py", line 109, in execution_control
    self._ec = ec_config_types[ec['option'].lower()](ec)
KeyError: 'kestrel'

The above exception was the direct cause of the following exception:
     sens_pa
Traceback (most recent call last):
  File "/projects/rev/environments/revruns/bin/least-cost-xmission", line 33, in <module>
    sys.exit(load_entry_point('NREL-reVX', 'console_scripts', 'least-cost-xmission')())
  File "/projects/rev/environments/revruns/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/projects/rev/environments/revruns/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/projects/rev/environments/revruns/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/projects/rev/environments/revruns/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/rev/environments/revruns/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/projects/rev/environments/revruns/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/kfs2/projects/rev/environments/gitrepos/reVX/reVX/least_cost_xmission/least_cost_xmission_cli.py", line 74, in from_config
    option = config.execution_control.option
  File "/kfs2/projects/rev/environments/gitrepos/reV/reV/config/base_analysis_config.py", line 117, in execution_control
    raise ConfigError(msg) from exc
reV.utilities.exceptions.ConfigError: Execution control option not recognized: "kestrel". Available options are: ['local', 'slurm', 'eagle'].
```

**Additional context**
Not critical since it seems to just be for AU reporting.

**Comment by ppinchuk** [comment]
For anyone going through this in the future, `"slurm"` is supposed to be the catchall option that you can use on any HPC with a SLURM submission system.

In practice, `"slurm"`, `"eagle"`, and `"kestrel"` are all interchangeable, since they all have the same effect of telling the code that you are running on a SLURM-based system.
