### ISSUE TITLE
Should raise `FileNotFoundError` sooner

### ISSUE THREAD

**Issue by ppinchuk** [NREL/reV#463]
In this code: 

https://github.com/NREL/reV/blob/a27dc0aa6348224fbab1954bc0bf2d8937beea7a/reV/supply_curve/cli_sc_aggregation.py#L52-L58

the hardcoded years lead to this error:

```
Traceback (most recent call last):
  File "/projects/rev/environments/revruns/lib/python3.11/site-packages/rex/resource.py", line 632, in __init__
    self._h5 = h5py.File(self.h5_file, mode=mode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/rev/environments/revruns/lib/python3.11/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/rev/environments/revruns/lib/python3.11/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/kfs2/pdatasets/WIND/conus/v1.0.0/wtk_conus_2017.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

This is confusing because of course WTK 2017 doesn't exist, and no one input 2017 as a year anywhere in the config. 

Probably should use the current calendar year as the upper bound? Or maybe 2100 to support sup3rCC?

In either case, the the break doesn't activate, a `FileNotFoundError` error should be raised without substituting the year.

**Comment by ppinchuk** [comment]
Fixed in #464
