### ISSUE TITLE
reV Generation Module Fails When Using SLURM on AWS ParallelCluster

### ISSUE THREAD

**Issue by ODOU** [NREL/reV#501]
## Issue Description
I'm analyzing RE potential in West Africa using reV to connect with the REEDS model for capacity expansion. Following the AWS ParallelCluster setup guide (https://nrel.github.io/reV/misc/examples.aws_pcluster.html), I've encountered an issue when switching to SLURM execution option.

### Current Behavior
- When using `execution_control: option= local`: Successfully generates h5 file in ~25 minutes for 300 sc points.
- When using `execution_control: option= slurm`: Fails to generate output h5 file
- Command used: `reV generation -c config_gen_WestAfrica.json`

### Expected Behavior
- The model should generate an h5 output file when run with SLURM execution mode on the AWS cluster

### Environment Details
AWS ParallelCluster Configuration:
- Region: us-west-2
- OS: Amazon Linux 2
- Head Node: t2.large
- Compute Nodes: c5.2xlarge (0-8 nodes)
- Scheduler: SLURM
- Shared Storage: 5000GB EBS (gp2) mounted at /shared

###  Multiple Error (s) found

---------------
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/hsds_env/lib/python3.8/site-packages/rex/utilities/utilities.py", line 336, in check_res_file
    with h5pyd.Folder(hsds_dir + '/') as f:
  File "/home/ec2-user/miniconda3/envs/hsds_env/lib/python3.8/site-packages/h5pyd/_hl/folders.py", line 204, in __init__
    rsp = self._http_conn.GET(req)
  File "/home/ec2-user/miniconda3/envs/hsds_env/lib/python3.8/site-packages/h5pyd/_hl/httpconn.py", line 480, in GET
    raise IOError("Connection Error")
OSError: Connection Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ec2-user/miniconda3/envs/hsds_env/lib/python3.8/site-packages/gaps/cli/config.py", line 594, in run_with_status_updates
    out = run_func(**run_kwargs)
  File "/shared/reV/reV/generation/generation.py", line 436, in __init__
    self._multi_h5_res, self._hsds = check_res_file(resource_file)
  File "/home/ec2-user/miniconda3/envs/hsds_env/lib/python3.8/site-packages/rex/utilities/utilities.py", line 351, in check_res_file
    raise FileNotFoundError(msg) from ex
FileNotFoundError: /nrel/nsrdb/meteosat/meteosat_2019.h5 is not a valid file path, and HSDS cannot be check for a file at this path:Connection Error!

------------------------------

### Attached Files
1. Full error log file
2. Configuration file (config_gen_WestAfrica.json)
3. start_hsds.sh script

I've tried various configuration options but haven't been able to resolve the issue. Any assistance would be greatly appreciated.

[config_gen_WestAfrica.json](https://github.com/user-attachments/files/18236792/config_gen_WestAfrica.json)
[westafrica_generation.log](https://github.com/user-attachments/files/18236793/westafrica_generation.log)
[westafrica_generation_j0_79.e.txt](https://github.com/user-attachments/files/18236813/westafrica_generation_j0_79.e.txt)

**Comment by ppinchuk** [comment]
I haven't had a chance to look into this properly yet, but an initial glance through your log file (`westafrica_generation_j0_79.e.txt`) suggests that the hsds setup script is not completing properly. Looks like the failure point is `cd ~/hsds/`, and it's failing with `/home/ec2-user/start_hsds.sh: line 58: cd: /home/ec2-user/hsds/: No such file or directory`. So maybe the `hsds` folder is not being properly copied to the EC2 instances?

**Comment by ODOU** [comment]
Thank for the reply. 
I checked once again, the folder exist and the path work if I use the command line (See sreenshot below).
![image](https://github.com/user-attachments/assets/02066957-93f8-40df-9fab-f8c968e2852e)

**Comment by ppinchuk** [comment]
Hello, sorry for the delayed response. 

Based on the log file you attached, it looks like your HSDS server is still not launching correctly. I think from here you have two options:

 1) The hsds startup shell script you are using is really outdated. See this [note](https://github.com/NREL/reV/tree/main/examples/aws_pcluster#setting-up-hsds-local-servers-on-your-compute-cluster:~:text=Note%20that%20these,rex%20docs%20page.):

> Note that these instructions were originally developed and tested in February 2022 and have not been maintained. The latest instructions for setting up HSDS local servers can be found in the rex docs page: [HSDS local server instructions](https://nrel.github.io/rex/misc/examples.hsds.html#setting-up-a-local-hsds-server). The best way to run reV on an AWS PCluster with HSDS local servers may be a combination of the instructions below and the latest instructions from the rex docs page.

If you want to continue pursuing this route, you will need to update the shell script to properly set up an HSDS server. We have some guidance on setting up a local HSDS server [here](https://nrel.github.io/rex/misc/examples.hsds.html#setting-up-a-local-hsds-server), but we do not maintain a single script that does this. 
 
2) We recently added [new capability](https://nrel.github.io/rex/misc/examples.fsspec.html) to specify S3 filepaths directly to reV. If you point to S3 filepaths, you wouldn't have to setup an HSDS server at all (though execution may be somewhat slower).

I think option 2 may be the easiest, but hopefully this gives you enough info to continue to make progress on this.

**Comment by ppinchuk** [comment]
Closing due to inactivity. If further questions come up, please reach out.
